package tree;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	AndTest.class,
	AndNestedTest.class,
	AnnotatedTest.class,
	AtMostOneTest.class,
	ClassAnnotatedTest.class,
	FieldAnnotatedTest.class,
	HasNoArgumentConstructorTest.class,
	MethodAnnotatedTest.class,
	MultipleOperatorsTest.class,
	NoneTest.class,
	OrTest.class
})
public class AllTests {
	// No Code Needed
}

