AnnaBot - Annotation Assertion Based Object Testing

Ian Darwin, http://www.darwinsys.com/

For a quick demo, run

java -classpath build:lib/javaee.jar:lib/darwinsys.jar annabot.AnnaBot claimclasses systestclasses

RUNNING ON ECLIPSE
------------------

To set up for developing and testing AnnaBot as an Eclipse
project, assuming you checked it out under Eclipse as a project:
1) Create a new JUnit 4 Run Configuration:
	Name: AnnaBot Unit Tests
	Class: AnnaBotTests

Run this; it should run > 50 tests and give a green bar.

2) Create a Java Application Configuration
	Name: AnnaBot System Tests
	Class: annabot.AnnaBot
	Arguments -> Application Arguments: claimclasses systestclasses

Run this; it should give output something like the following:

Using 7 claims from directory claimclasses
Checking 4 targets from directory systestclasses
AnnaBot: Initialization took 0.1 seconds
class violations.JPAEntityNoArgConstructor: JPA Entities must have a no-arg constructor
class violations.JPAEntityMethodFieldAnnotated: JPA Entity must have an ID
class violations.JPAEntityMethodFieldAnnotated: JPA Entities may have field OR method annotations, not both
class violations.JPAEntityHasId: JPA Entity must have an ID
class violations.JPAEntitySetMethodAnnotated: JPA Entities may have field OR method annotations, not both
AnnaBot: found 5 error(s) in 4 classes, time 0.3 seconds

Now you can dive in and start working on the code!

Remember: CVS update periodically. Send cvs diff -u (or Eclipse patch) diffs.

NETBEANS
--------
If you want it, nobody will stop you.
Better if you can send a "nbproject" folder
(as long as it doesn't embed any full paths!).

ANT
---
There is the outline of an Ant task but it
does not work as of this writing.

OTHER PROJECTS
--------------

You should be able to:
	jar up the "build" folder, add that jar to another project's classpath; 
	jar up the "claimclasses" but don't add that jar to classpath
	run AnnaBot with the claimclasses.jar and the target classes.

WRITING NEW CLAIMS
------------------
Each Claim class has three required methods:

	/* return the description of the problem this claim finds */
	public abstract String getDescription();
	
	/** Return a list of Operators that are the "if" part of
	 * a claim; if any of these operators fails, the class
	 * will be bypassed and considered successful for this claim.
	 */
	public abstract Operator[] getClassFilter();

	/** Return a list of Operators, all of which must return
	 * true for this class to be considered successful against
	 * this claim.
	 * Only called if the Operators in getClassFilter all pass.
	 */
	public abstract Operator[] getOperators();

Examine the existing claims folder for some examples.
Please contribute back to the project any claims that you 
develop for public APIs - thank you!

$Id$

