#!/bin/ksh

# ANNotation Assertion Based Object Testing for Java
# Ian F. Darwin, http://www.darwinsys.com/annabot

# In production this will be a Jar file...
ANNABOT_HOME=/home/ian/workspace/annabot/build

case $# in
0)	DIR=.;;
*)	DIR="$@"
esac

# TODO parse args

for d in ${DIR}
do
	echo === Starting $d ===
	(
	cd $d
	java -Ddebug.sourceutils \
		-classpath ${ANNABOT_HOME}:${HOME}/workspace/darwinsys-api/build:${CLASSPATH}:$PWD \
		annabot.AnnaBot \
			-jarDir ${HOME}/workspace.tcp/tcpseam/web/WEB-INF/lib/  \
			claims.JPAEntityMethodFieldClaims ${HOME}/workspace.tcp/tcpseam/build/classes
	)
done
